### ISSUE TITLE
update modules

### ISSUE THREAD

**Issue by serapath** [serapath/skilltrees#1]
## `@todo`
* [ ] rename https://github.com/wizardamigos/skilltree to `wizardamigos-skilltrees`
* [ ] make a wizardamigos theme and add it to that skilltree
* [ ] check https://github.com/ninabreznik/CryptoLife
* [ ] check https://github.com/ninabreznik/cryptolifePlay

---
